# version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CI=true
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    ports:
      - "9323:9323"  # Default Playwright port for viewing reports
    tty: true  # Keeps the container running
    # stdin_open: true  # Keeps STDIN open 

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins web interface
      - "50000:50000"  # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to run Docker commands
      - .:/var/jenkins_home/workspace/playwright-tests  # Mount your project
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    group_add:
      - "$(getent group docker | cut -d: -f3)"  # Add Jenkins to docker group
    depends_on:
      - playwright

volumes:
  jenkins_home: 